project:
  type: book
  output-dir: ../docs/github


book:
  title: "Version Control with Git and GitHub"
  author: 
    - Aud Halbritter
    - Richard J Telford
  date: today
  search: true
  repo-url: https://github.com/biostats-r/biostats
  repo-actions: [source]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - 1_Git_Tutorial.qmd
    - 2_Branch_Tutorials.qmd
    - 3_Fork_Tutorial.qmd 


format:
  html:
    theme: cosmo
    code-link: true
    css: "../css/style-chapters.css"

execute:
  echo: false
  out-width: '100%'
