project:
  type: book
  output-dir: ../docs/data_collection


book:
  title: "Data collection"
  author: 
    - Aud Halbritter
  favicon: ../figures/favicon.png
  date: today
  search: true
  repo-url: https://github.com/biostats-r/biostats
  sharing: [twitter, facebook]
  margin-header: "[![](https://biostats.w.uib.no/files/2020/01/biostats-button-res2.png 'bioST@TS | When biology adds up, at last&#8230;')](https://biostats.w.uib.no/)
   <br>[![](../figures/icons_all.png 'BioST@TS books'){width=250 height=50}](../index.html)"
  chapters:
    - index.qmd
    - 01_design-spreadsheets.qmd
    - 02_data_workflow.qmd
    - 03_data_curation.qmd
bibliography: bibliography.bib

highlight-style: a11y

format:
  html:
    code-tools: 
      source: true
      toggle: false
      caption: none
    theme: 
      light: [zephyr, ../css/custom.scss]
      dark: [zephyr, ../css/dark.scss, ../css/custom.scss]
    code-link: true

execute:
  echo: false
  out-width: '100%'
