project:
  type: book
  output-dir: ../docs/statisticsInR


book:
  title: "Statistics in R"
  author: 
   - Emily G Simmonds
   - Jonathan Soulé
   - Josh Lynn
   - Aud Halbritter
   - Richard J Telford
  date: today
  search: true
  repo-url: https://github.com/biostats-r/biostats
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - part: "Descriptive statistics"
      chapters:
        - 2.2_descriptive_statistics.qmd
    - part: "Regression models"
      chapters:
        - 2.1_simple_linear_regression.qmd
        - 2.X_introduction_to_GLMs.qmd
        - 2.X_binomial_GLM.qmd 


              
  

format:
  html:
    code-tools: 
      source: true
      toggle: false
      caption: none
    highlight-style: a11y
    theme: 
      light: [zephyr, ../css/custom.scss]
      dark: [zephyr, ../css/dark.scss, ../css/custom.scss]
    code-link: true
