project:
  type: book

book:
  title: "Enough Markdown to Write a Thesis"
  author: "Richard J Telford"
  date: today
  chapters:
    - index.qmd
    - part: firstSteps.qmd
      chapters:
      - gettingStarted.qmd
      - elements.qmd
      - figuresTables.qmd
    - part: towardsAthesis.qmd
      chapters:
        - bibcite.qmd
        - crossReference.qmd
        - journalFormatting.qmd
        - presentations.qmd
    - part: finalPart.qmd
      chapters:
        - otherTopics.qmd
        - troubleshooting.qmd
        - furtherReading.qmd

bibliography: reproducibility.bib

format:
  html:
    theme: cosmo
    code-link: true
    css: "css/style-chapters.css"


