project:
  type: book
  output-dir: ../docs/quarto


book:
  title: "Enough Markdown to Write a Thesis"
  author: "Richard J Telford"
  date: today
  search: true
  repo-url: https://github.com/biostats-r/biostats
  repo-actions: [source]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - part: "First Steps with Quarto"
      chapters:
      - gettingStarted.qmd
      - elements.qmd
      - figuresTables.qmd
    - part: "Towards a Thesis"
      chapters:
        - bibcite.qmd
        - crossReference.qmd
        - journalFormatting.qmd
        - presentations.qmd
    - part: "Fixing problems"
      chapters:
        - otherTopics.qmd
        - troubleshooting.qmd
        - furtherReading.qmd

bibliography: reproducibility.bib
suppress-bibliography: true

format:
  html:
    theme: cosmo
    code-link: true
    css: "css/style-chapters.css"


