project:
  type: book
  output-dir: ../docs/workingInR


book:
  title: "Working in R"
  favicon: ../figures/favicon.png
  author: 
   - Jonathan Soulé
   - Aud Halbritter
   - Richard J Telford.
  date: today
  search: true
  repo-url: https://github.com/biostats-r/biostats
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - part: "Setting up R and RStudio"
      chapters:
        - 0010_Getting_Started_with_RStudio.qmd
        - 0011_projects.qmd
        - 0012_scripts.qmd
        - 0013_packages.qmd
    - part: "First steps in R"
      chapters:
        - 002_First_Steps_in_R.qmd
        - 005_Importing_Data_in_R.qmd
    - part: "Data manipulation with the tidyverse"
      chapters:
        - 010-pipes.qmd
        - 011-tidyr-pivot.qmd
        - 012-dplyr-single-table.qmd
        - 013-dplyr-multiple-tables.qmd
    - part: "Data Visualisation"
      chapters:
        - 100_why_data_visualisation.qmd
        - 101_getting_started_with_ggplot.qmd
        - 103_different_types_of_vizualization.qmd
        - 118_themes.qmd
        - 120_colour_shape_linetypes.qmd
        - 125_ggplot_regression.qmd
        - 130_patchwork.qmd
        - 140_maps.qmd
    - part: "Other Topics"
      chapters:
        - 050_missing_values.qmd
        - 060_bestiary.qmd


format:
  html:
    code-tools: 
      source: true
      toggle: false
      caption: none
    highlight-style: a11y
    theme: 
      light: [zephyr, ../css/custom.scss]
      dark: [zephyr, ../css/dark.scss, ../css/custom.scss]
    code-link: true
    css: [include/webex.css]
    include-after-body: [include/webex.js]

execute: 
  freeze: auto
  