project:
  type: book
  output-dir: ../docs/workingInR


book:
  title: "Working in R"
  description: An introduction to working in R with a focus on tidyverse
  author: 
   - Jonathan Soulé
   - Aud Halbritter
   - Richard J Telford.
  date: today
  search: true
  repo-url: https://github.com/biostats-r/biostats
  repo-actions: [source]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - part: "Setting up R and RStudio"
      chapters:
        - 001_Getting_Started_with_R.qmd
 #    - part: "First steps in R"
 #      chapters:
 #      - 002_First_Steps_in_R.qmd
 #      - 005_Importing_Data_in_R.qmd
 #    - part: "Data manipulation with the tidyverse"
 #      chapters:
 #       - 010-pipes.qmd
 #       - 011-tidyr-pivot.qmd
 #       - 012-dplyr-single-table.qmd
 #       - 013-dplyr-multiple-tables.qmd
 #    - part: "Data Visualisation"
 #      chapters:
 #      - 100_why_data_visualisation.qmd
 #      - 101_getting_started_with_ggplot.qmd
 #      - 103_different_types_of_vizualization.qmd
 #      - 118_themes.qmd
 #      - 120_colour_shape_linetypes.qmd
 #      - 125_ggplot_regression.qmd
 #      - 130_patchwork.qmd
 #    - part: "Other Topics"
 #      chapters:
 # #     - 045-functions-packages.qmd
 #      - 050_missing_values.qmd
 #      - 060_bestiary.qmd


format:
  html:
    highlight-style: a11y
    theme: 
      light: flatly
      dark: darkly
    code-link: true
    css: "../css/style.css"


