project:
  type: book
  output-dir: ../docs/package


book:
  title: "Writing an R package"
  author: "Richard J Telford"
  favicon: ../figures/favicon.png
  date: today
  search: true
  repo-url: https://github.com/biostats-r/biostats
  sharing: [twitter, facebook]
  margin-header: "[![](https://biostats.w.uib.no/files/2020/01/biostats-button-res2.png 'bioST@TS | When biology adds up, at last&#8230;')](https://biostats.w.uib.no/)
   <br>[![](../figures/icons_all.png 'BioST@TS books'){width=250 height=50}](../index.html)"
  chapters:
    - index.qmd
    - 01-system-setup.qmd
    - 02-package-infrastructure.qmd
    - 03-package-contents.qmd
    - 04-more-documentation.qmd
    - 05-distributing.qmd
    - 06-troubleshooting.qmd


highlight-style: a11y

format:
  html:
    code-tools: 
      source: true
      toggle: false
      caption: none
    theme: 
      light: [zephyr, ../css/custom.scss]
      dark: [zephyr, ../css/dark.scss, ../css/custom.scss]
    code-link: true

execute: 
  eval: false
  echo: true


