project:
  type: book
  output-dir: ../docs/package


book:
  title: "Writing an R package"
  author: "Richard J Telford"
  date: today
  search: true
  repo-url: https://github.com/biostats-r/biostats
  repo-actions: [source]
  sharing: [twitter, facebook]
  chapters:
    - index.qmd
    - 01-system-setup.qmd
    - 02-package-infrastructure.qmd
    - 03-package-contents.qmd
    - 04-more-documentation.qmd
    - 05-distributing.qmd
    - 06-troubleshooting.qmd


format:
  html:
    theme: cosmo
    code-link: true
    css: "../css/style-chapters.css"
    
execute: 
  eval: false
  echo: true


