project:
  type: book
  output-dir: ../docs/


book:
  title: "Enough R to write a thesis"
  subtitle: "From raw data to finished thesis"
  date: today
  search: true
  repo-url: https://github.com/biostats-r/biostats
  sharing: [twitter, facebook]
  chapters:
    - index.qmd


format:
  html:
    code-tools: 
      source: true
      toggle: false
      caption: none
    highlight-style: a11y
    theme: 
      light: [zephyr, ../css/custom.scss]
      dark: [zephyr, ../css/dark.scss, ../css/custom.scss]
    code-link: true
    number-sections: false
    
execute: 
  echo: false
